name: Deploy to lambda
on: workflow_dispatch
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEY }}
          aws-region: us-east-1


      - name: Zip Artifact
        run: | 
          echo "current build number is ${{github.run_number}}"
          pwd
          ls -al
          echo "present dir is"
          mkdir serverless
            cd  serverless
            pwd
            cp ../*.js .
            cd nodejs-webapp
            pwd
            cd ..
            zip -r ../csye6225-lambda.zip *
            ls

      - name: Upload Artifact to S3
        run: |
            pwd
            ls -al
            aws configure list
            aws s3 cp csye6225-lamda.zip s3://${{secrets.S3_SERVERLESS_BUCKET}} --sse

      - name: Lambda Update Call
        run: |
            aws lambda update-function-code \
            --function-name  csye6225 \
            --output json \
            --s3-location bucket=${{secrets.S3_SERVERLESS_BUCKET}},bundleType=zip,key=csye6225-lambda.zip
            --file-exists-behavior OVERWRITE
            echo $output