name: Deploy Lamda
 
env: 
 DEPLOY_FUNCTION_NAME: csye6225
 AWS_REGION: us-east-1
 CODEDEPLOY_APPLICATION_NAME: csye6225-lambda-appname
 CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-lambda-deployment 
 ARTIFACT_NAME: csye6225-lambda.zip
 
on:
   push:
    branches: [ main ]
 
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    
    - name: Build Deployment Artifact
      run: |
         zip -r csye6225-prod.zip index.js
      
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
 
    - name: Update Lambda Function
      run: |
          aws lambda get-alias --function-name ${{ env.DEPLOY_FUNCTION_NAME }} --name lambdaalias > output.json 
          DEVELOPMENT_ALIAS_VERSION=$(cat output.json | jq -r '.FunctionVersion')
          echo $DEVELOPMENT_ALIAS_VERSION
          aws lambda update-function-code --function-name ${{ env.DEPLOY_FUNCTION_NAME }} --zip-file fileb://csye6225-prod.zip --publish > output.json
          LATEST_VERSION=$(cat output.json | jq -r '.Version')
          echo $LATEST_VERSION
          cat > "appspec.yml" <<- EOM
          version: 0.0
          Resources:
          - myLambdaFunction:
            Type: AWS::Lambda::Function
            Properties:
              Name: "$DEPLOY_FUNCTION_NAME"
              Alias: "lambdaalias"
              CurrentVersion: $DEVELOPMENT_ALIAS_VERSION
              TargetVersion: $LATEST_VERSION
            EOM
          cat appspec.yml 
 
    - name: Copy Artifact to S3
      run: |
          aws s3 cp appspec.yml s3://${{ secrets.S3_SERVERLESS_BUCKET }} 
 
    - name: Codedeploy API call
      run: |
          REVISION=revisionType=S3,s3Location={bucket=${{ secrets.S3_SERVERLESS_BUCKET }},key=appspec.yml,bundleType=YAML}
          output=$(aws deploy create-deployment \
          --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} \
          --deployment-config-name CodeDeployDefault.LambdaAllAtOnce \
          --revision $REVISION)
          echo $output
          deployment_id=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $deployment_id
