name: Deploy to lambda
on: workflow_dispatch

jobs:
  deploy_source:

    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [10.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install npm
        run: npm install

      - name: install sam cli
        uses: advancedcsg-open/action-setup-sam@v1
        run: sam --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Zip Artifact
        run: | 
          echo "current build number is ${{github.run_number}}"
          pwd
          ls -al
          echo "present dir is"
          mkdir serverless
            cd  serverless
            pwd
            cp ../*.js .
            pwd
            cd ..
            zip -r ../csye6225-lambda.zip *
            ls

     